### ISSUE TITLE
Firefox: Login redirects to robots.txt / 404

### ISSUE THREAD

**Issue by knoobie** [vaadin/full-stack-starter#17] opened 2018-09-07 11:44 UTC
Firefox (61+) sometimes (often first login after restarting the browser) redirects the user to /robots.txt instead of the storefront.

![grafik](https://user-images.githubusercontent.com/3968629/45217320-f420be00-b2a3-11e8-9935-143a1eec0345.png)

**Comment by alvarezguille** [comment] 2018-09-07 12:34
@knoobie thanks for reporting this, I wasn't able to reproduce. And I'm starting to believe that maybe it's related to some Firefox add-on requesting `robots.txt` file.
That could be verified by testing with disabled addons or maybe in private browsing mode.

Independent of reproducibility this behavior can be prevented by adding `/robots.txt` to the Spring Security bypass configuration. 
That is in `SecurityConfiguration.java` in the method `public void configure(WebSecurity web) throws Exception {` add the String `"/robots.txt"` to the `web.ignoring().antMatchers` args.

Something like:
```
		web.ignoring().antMatchers(
				// the robots exclusion standard
				"/robots.txt",

				// Vaadin Flow static resources
				"/VAADIN/**",

				// the standard favicon URI
				"/favicon.ico",
...

```

We will include this change in the starter after corresponding tests

**Comment by knoobie** [comment] 2018-09-07 12:53
@alvarezguille thank you for looking at that! The only addon that is installed is [wappalyzer](https://www.wappalyzer.com/). 

I think you are right, the addon is used to crawl webpages.

**Comment by alvarezguille** [comment] 2018-09-07 13:02
Wappalyzer seems to be the source of the request indeed https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/driver.js#L293-L342

I'll close the issue.

**Closed by alvarezguille** 2018-09-07 13:02 UTC
